spring.application.name=bookReservationAPI

#spring.datasource.url=jdbc:h2:mem:BRDB;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
#spring.datasource.username=sa
#spring.datasource.password=
#spring.datasource.driver-class-name=org.h2.Driver
#
#spring.jpa.hibernate.ddl-auto=update
#
#spring.jpa.show-sql=true
#spring.jpa.properties.hibernate.format_sql=true
#
#spring.h2.console.enabled=false
#spring.h2.console.path=/h2-console

#spring.config.activate.on-profile=docker

# MySQL Configuration
# husk tjek mydb?
spring.datasource.url=jdbc:mysql://db:3306/BRDB?createDatabaseIfNotExist=true
spring.datasource.username=user
spring.datasource.password=secret
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect
spring.jpa.show-sql=true

rsa.public-key=file:keys/public.pem
rsa.private-key=file:keys/private.pem